- name: Install Java
  ansible.builtin.apt:
    name: openjdk-17-jdk
    state: present
    update_cache: true

- name: Remove old Jenkins repository
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/jenkins.list
    state: absent

- name: Remove old Jenkins key
  ansible.builtin.file:
    path: /usr/share/keyrings/jenkins-keyring.asc
    state: absent

- name: Download Jenkins key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add Jenkins repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    filename: jenkins
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present

- name: Start Jenkins
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: true
