# docker-compose.yml
version: "3.9"

services:

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: systeme_reparti
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: flask_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/systeme_reparti
      SECRET_KEY: supersecurelongsecretkeywithatleast32chars!
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
